# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c190f5a3ad11171a5f6140b73cad5be7"
name = "Shipmatic"
application_url = "https://pubmed-trustees-thou-eclipse.trycloudflare.com"
embedded = true
handle = "shipmatic-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_publications,write_publications"

[auth]
redirect_urls = ["https://pubmed-trustees-thou-eclipse.trycloudflare.com/auth/callback", "https://pubmed-trustees-thou-eclipse.trycloudflare.com/auth/shopify/callback", "https://pubmed-trustees-thou-eclipse.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
