# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de621c8c41ba70a62f1d5a3a188fca4e"
name = "shipment"
application_url = "https://swimming-kept-females-photographer.trycloudflare.com"
embedded = true
handle = "shipment-11"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_publications,write_publications,read_orders,write_orders,read_customers"

[auth]
redirect_urls = ["https://swimming-kept-females-photographer.trycloudflare.com/auth/callback", "https://swimming-kept-females-photographer.trycloudflare.com/auth/shopify/callback", "https://swimming-kept-females-photographer.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
[app_proxy]
url = "https://swimming-kept-females-photographer.trycloudflare.com/app"
subpath = "shipment"
prefix = "apps"
